[package]
name = "image-resizer"
version = "0.1.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/xcompress"
homepage = "https://magiclen.org/xcompress"
keywords = ["image", "resize", "shrink", "sharpen"]
categories = ["command-line-utilities"]
description= "Resize or just shrink images and sharpen them appropriately."
readme = "README.md"
license = "MIT"

[badges.travis-ci]
repository = "magiclen/image-resizer"
branch = "master"

[profile.release]
panic = "abort"

[dependencies]
clap = "2.33.0"
image-convert = "0.9.1"
num_cpus = "1.10.0"
terminal_size = "0.1"
path-absolutize = "1.1.3"
scanner-rust = "1.0.6"
starts-ends-with-caseless = "0.5"
walkdir = "2"
pathdiff = "0.1.0"
threadpool = "1.7.1"